name: Sync Website Data

on:
  schedule:
    # Run once daily at midnight UTC to sync data from Google Sheets
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Sync from Google Sheets
      env:
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GITHUB_ACTIONS: true
      run: |
        # Run sync script (credentials are passed via environment variables)
        python sync_website.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add data/products.json images/
          git commit -m "Daily sync: Update products from Google Sheets [skip ci]"
          git push
          echo "✅ Changes pushed successfully"
        fi
